version: 2.1
orbs:
  node: circleci/node@14.17
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    working_directory: ~/project
    steps:
      - checkout
      - run: node --version
      - run: go version
      - add_ssh_keys:
          fingerprints:
            - "eb:f4:55:61:be:f2:6b:17:79:a4:b0:55:39:83:1d:cb"
      - run:
          name: "config"
          command: |
            sudo apt-get update 
            sudo apt-get install rsync
            ssh-keyscan ${ServerHost} >> ~/.ssh/known_hosts
            export GOPRIVATE="github.com/ohayao"
            git config --global url."https://ohayao:${token}@github.com/ohayao".insteadOf "https://github.com/ohayao"
          # curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          # sudo apt-get install -y nodejs
      - run:
          name: "build service application 'hello_app'"
          command: |
            cd service
            go build -o hello_app app.go
            cd ..
      - run:
          name: "npm run build 发布后台ui文件"
          command: |
            cd ui
            npm install
            npm run build
            cd ..
      - run:
          name: "sync project"
          command: |
            rsync -e "ssh -o StrictHostKeyChecking=no" \
            --exclude 'ui/node_modules' \
            -av ./ \
            ${ServerUser}@${ServerHost}:/${ServerUser}/backstage
      - run:
          name: "rerun service application"
          command: |
            ssh ${ServerUser}@${ServerHost} "kill -9 \$(lsof -i:8090 |grep hello_app |grep \(LISTEN\) |awk '{print $2}') > /dev/null 2>&1 &"
            ssh ${ServerUser}@${ServerHost} "cd ~/backstage/service; nohup ./hello_app >> ../backlogs.log 2>&1 &"
workflows:
  version: 2
  build_production:
    jobs:
      - build:
          context:
            - Github
            - Server
          filters:
            branches:
              only:
                - master
  build_development:
    jobs:
      - build:
          context:
            - Github
            - Server
          filters:
            branches:
              ignore:
                - master
