version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    working_directory: ~/project
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "eb:f4:55:61:be:f2:6b:17:79:a4:b0:55:39:83:1d:cb"
      - run:
          name: "config"
          command: |
            sudo apt-get update 
            sudo apt-get install rsync
            ssh-keyscan ${ServerHost} >> ~/.ssh/known_hosts
            export GOPRIVATE="github.com/ohayao"
            git config --global url."https://ohayao:${token}@github.com/ohayao".insteadOf "https://github.com/ohayao"
      - run:
          name: "build service application 'hello_app'"
          command: |
            cd service
            go build -o hello_app app.go
            cd ..
      - run:
          name: "sync project"
          command: |
            rsync -e "ssh -o StrictHostKeyChecking=no" \
            -av ./ \
            ${ServerUser}@${ServerHost}:/${ServerUser}/backstage
      - run:
          name: "rerun service application"
          command: |
            ssh ${ServerUser}@${ServerHost} 'lsof -i:8090 |grep hello_app |grep \(LISTEN\) |awk "{print $2}" >> aaaaab.txt'
            ssh ${ServerUser}@${ServerHost} "lsof -i:8090 |grep hello_app |grep \(LISTEN\) |awk '{print $2}' >> aaaaab.txt"
            ssh ${ServerUser}@${ServerHost} 'lsof -i:8090 |grep hello_app |grep \(LISTEN\) |awk '{print $2}' >> aaaaab.txt'

            ssh ${ServerUser}@${ServerHost} \
            "lsof -i:8090 |grep hello_app |grep \(LISTEN\) |awk '{print $2}' >> aaaaaa.txt; if [ $(lsof -i:8090 |grep hello_app |grep \(LISTEN\) |awk '{print $2}') ]; \
            then kill -9 $(lsof -i:8090 |grep hello_app |grep \(LISTEN\) |awk '{print $2}') >> aaaaaa.txt;fi; \
            nohup ~/backstage/service/hello_app >> ~/backstage/backlogs.log 2>&1 &
            "
            ssh ${ServerUser}@${ServerHost} \
            "nohup ~/backstage/service/hello_app >> ~/backstage/backlogs.log 2>&1 &"
workflows:
  version: 2
  build_production:
    jobs:
      - build:
          context:
            - Github
            - Server
          filters:
            branches:
              only:
                - master
  build_development:
    jobs:
      - build:
          context:
            - Github
            - Server
          filters:
            branches:
              ignore:
                - master
